services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portal-rh-backend
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: 6i0OpRKMzBWlm4NHUgZXlv4GP4JO9S
      EMAIL_USER: chouchene.amine.etud@gmail.com
      EMAIL_PASS: rzrt khzc rucz byhy
      SYSTEM_PASSWORD: Systeme123!

      FRONTEND_URL: http://localhost:4200
      COMPANY_NAME: ArabSoft
      COMPANY_ADDRESS: Rue de la République, Tunis, Tunisia
      COMPANY_PHONE: +216 71 234 567
      COMPANY_MAT: 123456/A/M/000
      COMPANY_CNSS: ""
      COMPANY_LOGO_URL: https://www.arabsoft.com.tn/smart/themes/default/assets/img/logo_svg.svg
      PORT: 3000
      TOKEN: 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
      ENDPOINT: https://models.github.ai/inference
      MODEL: openai/gpt-4.1
    volumes:
      - .:/usr/src/app
    networks:
      - portal-network

networks:
  portal-network:
    name: portal-network
    driver: bridge
